# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           go-plugin
%define go_import_path  github.com/knqyf263/go-plugin
# The upstream WASM test artifacts are generated by the Makefile and are not
# included in the source archive. - Jvle
%define go_test_exclude %{shrink:
    %{go_import_path}/examples/helloworld
    %{go_import_path}/examples/host-function-library
    %{go_import_path}/examples/host-functions
    %{go_import_path}/examples/known-types
    %{go_import_path}/examples/wasi
    %{go_import_path}/tests/fields
    %{go_import_path}/tests/host-functions
    %{go_import_path}/tests/import
    %{go_import_path}/tests/well-known
}

Name:           go-github-knqyf263-go-plugin
Version:        0.9.0
Release:        %autorelease
Summary:        Extensible WebAssembly plugin framework for Go
License:        Apache-2.0
URL:            https://github.com/knqyf263/go-plugin
#!RemoteAsset:  sha256:e5157c45c84079ef0f2f4542e5e28f1126c6a71b77f17f3da425a55ac6acd9ef
Source0:        https://github.com/knqyf263/go-plugin/archive/v%{version}.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildRequires:  go
BuildRequires:  go-rpm-macros
# It seems that the API changed after v0.6.0
BuildRequires:  go(github.com/planetscale/vtprotobuf) = 0.4.0
BuildRequires:  go(github.com/stretchr/testify)
BuildRequires:  go(github.com/tetratelabs/wazero)
BuildRequires:  go(google.golang.org/protobuf)

Provides:       go(github.com/knqyf263/go-plugin) = %{version}

Requires:       go(github.com/planetscale/vtprotobuf) = 0.4.0
Requires:       go(github.com/tetratelabs/wazero)
Requires:       go(google.golang.org/protobuf)

%description
go-plugin is an extensible WebAssembly plugin framework for Go.

%files
%doc README.md
%license LICENSE
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
