# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           trace
%define go_import_path  go.opentelemetry.io/otel/trace
%define go_source_subdir trace

Name:           go-opentelemetry-otel-trace
Version:        1.43.0
Release:        %autorelease
Summary:        Go module dependency for Prometheus
License:        Apache-2.0
URL:            https://github.com/open-telemetry/opentelemetry-go
#!RemoteAsset:  sha256:20cac3587b683230b161e46c2b73deef53e2a5fb3b7a13f0900ebd22b685d60c
Source0:        https://github.com/open-telemetry/opentelemetry-go/archive/refs/tags/trace/v1.43.0.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildOption(prep):  -n opentelemetry-go-trace-v1.43.0
# This package owns a Go module below the repository root; the explicit
# %%install/%%check sections below copy only %%{go_source_subdir}, because
# the default golangmodules phases would copy the full archive under
# %%{go_import_path} and create invalid import paths.
# Nested Go modules have their own module path/dependencies; skip them in %check
# so the parent package does not try to test unrelated internal tools.
%define go_test_exclude_glob %{go_import_path}/internal/telemetry/test*

BuildRequires:  go
BuildRequires:  go(github.com/cespare/xxhash/v2)
BuildRequires:  go(github.com/davecgh/go-spew)
BuildRequires:  go(github.com/google/go-cmp)
BuildRequires:  go(github.com/google/go-cmp/cmp)
BuildRequires:  go(github.com/pmezard/go-difflib)
BuildRequires:  go(github.com/stretchr/testify)
BuildRequires:  go(github.com/stretchr/testify/assert)
BuildRequires:  go(github.com/stretchr/testify/require)
BuildRequires:  go(go.opentelemetry.io/otel/attribute)
BuildRequires:  go(go.opentelemetry.io/otel/codes)
BuildRequires:  go(go.opentelemetry.io/otel/semconv/v1.40.0)
BuildRequires:  go(gopkg.in/yaml.v3)
BuildRequires:  go-rpm-macros

Provides:       go(go.opentelemetry.io/otel/trace) = %{version}
Provides:       go(go.opentelemetry.io/otel/trace/embedded) = %{version}
Provides:       go(go.opentelemetry.io/otel/trace/internal/telemetry) = %{version}
Provides:       go(go.opentelemetry.io/otel/trace/noop) = %{version}

Requires:       go(github.com/cespare/xxhash/v2)
Requires:       go(go.opentelemetry.io/otel/attribute)
Requires:       go(go.opentelemetry.io/otel/codes)
Requires:       go(go.opentelemetry.io/otel/semconv/v1.40.0)

%description
Go module dependency for Prometheus. Generated by go2spec.

%install
pushd %{go_source_subdir}
%buildsystem_golangmodules_install
popd

%check
pushd %{go_source_subdir}
%buildsystem_golangmodules_check
popd

%files
%doc trace/README.md
%license LICENSE
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
