# SPDX-FileCopyrightText: (C) 2025 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025 openRuyi Project Contributors
# SPDX-FileContributor: Zheng Junjie <zhengjunjie@iscas.ac.cn>
# SPDX-FileContributor: misaka00251 <liuxin@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           findutils
Version:        4.10.0
Release:        %autorelease
Summary:        The GNU versions of find utilities (find and xargs)
License:        GPL-3.0-or-later
URL:            https://www.gnu.org/software/findutils/
VCS:            git:https://https.git.savannah.gnu.org/git/findutils.git
#!RemoteAsset
Source0:        https://ftpmirror.gnu.org/gnu/%{name}/%{name}-%{version}.tar.xz
#!RemoteAsset
Source1:        https://ftpmirror.gnu.org/gnu/%{name}/%{name}-%{version}.tar.xz.sig
#!RemoteAsset
Source2:        https://savannah.gnu.org/project/release-gpgkeys.php?group=%{name}&download=1&file=./%{name}.keyring
BuildSystem:    autotools

# adds a new option -xautofs to find to not descend into directories on autofs file systems
Patch0:         findutils-xautofs.patch
# https://git.savannah.gnu.org/cgit/findutils.git/commit/?id=e5d6eb919b9
Patch1:         findutils-avoid-crash-system-loop.patch

BuildOption(conf): --libexecdir=%{_libdir}/find
BuildOption(conf): --localstatedir=%{_localstatedir}/lib

BuildRequires:  automake
# BuildRequire dejagnu for 'runtest' to execute all tests.
BuildRequires:  dejagnu
BuildRequires:  texinfo
BuildRequires:  libselinux-devel

Provides:       find = %{version}-%{release}

%description
The findutils package contains programs which will help you locate
files on your system.  The find utility searches through a hierarchy
of directories looking for files which match a certain set of criteria
(such as a file name pattern).  The xargs utility builds and executes
command lines from standard input arguments (usually lists of file
names generated by the find command).

You should install findutils because it includes tools that are very
useful for finding things on your system.

%install -a
rm -f %{buildroot}%{_infodir}/find-maint*

rm %{buildroot}%{_bindir}/locate
rm %{buildroot}%{_bindir}/updatedb
rm -r %{buildroot}%{_libdir}/find
rm %{buildroot}%{_mandir}/man1/locate.1*
rm %{buildroot}%{_mandir}/man1/updatedb.1*
rm %{buildroot}%{_mandir}/man5/locatedb.5*
%find_lang %{name} --generate-subpackages

%files
%license COPYING
%doc AUTHORS NEWS README THANKS TODO
%{_bindir}/find
%{_bindir}/xargs
%{_infodir}/find.info*.gz
%{_mandir}/man1/find.1%{?ext_man}
%{_mandir}/man1/xargs.1%{?ext_man}

%changelog
%autochangelog
