# SPDX-FileCopyrightText: (C) 2025 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025 openRuyi Project Contributors
# SPDX-FileContributor: Jingwiw <wangjingwei@iscas.ac.cn>
# SPDX-FileContributor: Zheng Junjie <zhengjunjie@iscas.ac.cn>
# SPDX-FileContributor: yyjeqhc <1772413353@qq.com>
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           audit
Version:        4.0.2
Release:        %autorelease
Summary:        Linux kernel audit subsystem utilities
License:        GPL-2.0-or-later AND LGPL-2.1-or-later
URL:            https://people.redhat.com/sgrubb/audit/
#!RemoteAsset
Source:        https://people.redhat.com/sgrubb/audit/%{name}-%{version}.tar.gz

BuildSystem:    autotools
BuildOption(conf): --libexecdir=%{_libexecdir}/%{name}
BuildOption(conf): --with-apparmor
BuildOption(conf): --with-libcap-ng=no
BuildOption(conf): --disable-static
BuildOption(conf): --with-python3=no
BuildOption(conf): --disable-zos-remote

BuildRequires:  autoconf >= 2.12
BuildRequires:  linux-headers >= 2.6.30
BuildRequires:  libtool
BuildRequires:  pkgconfig
Requires:       gawk

%description
The audit package contains the user space utilities for storing and
processing the records generated by the audit subsystem in the
Linux kernel. This package contains the runtime libraries and user space tools.

%package devel
Summary:        Header files for the audit framework
License:        LGPL-2.1-or-later
Requires:       %{name} = %{version}

%description devel
The audit-devel package contains the header files and development libraries
needed for developing applications that use the audit framework.

%conf -p
autoreconf -fi
export CFLAGS="%{optflags} -fno-strict-aliasing"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-Wl,-z,relro,-z,now"

%install -a
rm -rf %{buildroot}/%{_mandir}/man[578]
mkdir -p %{buildroot}/%{_mandir}/man5
install -m 0644 docs/libaudit.conf.5 %{buildroot}/%{_mandir}/man5
install -m 0644 init.d/libaudit.conf %{buildroot}%{_sysconfdir}
install -D -m 0644 ./m4/audit.m4  %{buildroot}%{_datadir}/aclocal/audit.m4

install -d -m 750 %{buildroot}%{_sysconfdir}/audisp/plugins.d

find %{buildroot} -type f -name "*.la" -delete -print

# TODO: make test pass.
%check

%files
%license COPYING
# Merged files from libaudit1
%{_libdir}/libaudit.so.1
%{_libdir}/libaudit.so.1.*
%config(noreplace) %attr(640,root,root) %{_sysconfdir}/libaudit.conf
%{_libdir}/libauparse.so.0
%{_libdir}/libauparse.so.0.*

%{_sbindir}/*
%{_libexecdir}/%{name}/*
%config(noreplace) %{_sysconfdir}/audit/*
%attr(750,root,root) %dir %{_sysconfdir}/audisp
%attr(750,root,root) %dir %{_sysconfdir}/audisp/plugins.d

%{_bindir}/aulast
%{_bindir}/aulastlog
%{_bindir}/ausyscall

%{_unitdir}/audit-rules.service
%{_unitdir}/auditd.service

%dir %{_datadir}/audit-rules
%{_datadir}/audit-rules/*.rules
%{_datadir}/audit-rules/README-rules

%{_mandir}/man*/*

%files devel
%doc contrib/plugin
%{_libdir}/libaudit.so
%{_libdir}/libauparse.so
%{_includedir}/libaudit.h
%{_includedir}/audit_logging.h
%{_includedir}/audit-records.h
%{_includedir}/auparse.h
%{_includedir}/auparse-defs.h
%{_datadir}/aclocal/audit.m4
%{_libdir}/pkgconfig/audit.pc
%{_libdir}/pkgconfig/auparse.pc
%{_mandir}/man3/*

%changelog
%{?autochangelog}
