# SPDX-FileCopyrightText: (C) 2025 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025 openRuyi Project Contributors
# SPDX-FileContributor: Jingwiw <wangjingwei@iscas.ac.cn>
# SPDX-FileContributor: Zheng Junjie <zhengjunjie@iscas.ac.cn>
# SPDX-FileContributor: yyjeqhc <jialin.oerv@isrc.iscas.ac.cn>
# SPDX-FileContributor: misaka00251 <liuxin@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%bcond golang 1

Name:           audit
Version:        4.1.4
Release:        %autorelease
Summary:        Linux kernel audit subsystem utilities
License:        GPL-2.0-or-later AND LGPL-2.1-or-later
URL:            https://people.redhat.com/sgrubb/audit/
VCS:            git:https://github.com/linux-audit/audit-userspace
#!RemoteAsset:  sha256:8396544ea08c69b39f5c00027549394f2149b31c4a9e693097d6ce134f3ffe3d
Source:         https://github.com/linux-audit/audit-userspace/archive/refs/tags/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
BuildSystem:    autotools

# Backport from https://github.com/linux-audit/audit-userspace/commit/13e79b7d2c4aa833129487c4cb5837df08e94e77
Patch0:         0001-put-bash-completions-in-bash-completions-dir.patch

BuildOption(conf):  --libexecdir=%{_libexecdir}/%{name}
BuildOption(conf):  --with-apparmor
BuildOption(conf):  --with-libcap-ng=no
BuildOption(conf):  --disable-static
BuildOption(conf):  --with-python3=no
%if %{without golang}
BuildOption(conf):  --with-golang=no
%endif
BuildOption(conf):  --disable-zos-remote

BuildRequires:  autoconf >= 2.12
BuildRequires:  linux-headers >= 2.6.30
BuildRequires:  libtool
BuildRequires:  pkgconfig
BuildRequires:  pkgconfig(bash-completion)

Requires:       gawk

%description
The audit package contains the user space utilities for storing and
processing the records generated by the audit subsystem in the
Linux kernel. This package contains the runtime libraries and user space tools.

%package        devel
Summary:        Header files for the audit framework
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description    devel
The audit-devel package contains the header files and development libraries
needed for developing applications that use the audit framework.

%conf -p
autoreconf -fiv
export CFLAGS="%{optflags} -fno-strict-aliasing"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-Wl,-z,relro,-z,now"

%install -a
rm -rf %{buildroot}/%{_mandir}/man[578]
mkdir -p %{buildroot}/%{_mandir}/man5
install -m 0644 docs/libaudit.conf.5 %{buildroot}/%{_mandir}/man5
install -m 0644 init.d/libaudit.conf %{buildroot}%{_sysconfdir}
install -D -m 0644 ./m4/audit.m4  %{buildroot}%{_datadir}/aclocal/audit.m4

install -d -m 750 %{buildroot}%{_sysconfdir}/audisp/plugins.d
# Better naming
mv %{buildroot}%{bash_completions_dir}/audit.bash_completion %{buildroot}%{bash_completions_dir}/audit

%files
%license COPYING
%{_bindir}/aulast
%{_bindir}/aulastlog
%{_bindir}/ausyscall
%{_sbindir}/*
# Merged files from libaudit1
%{_libdir}/libaudit.so.1
%{_libdir}/libaudit.so.1.*
%config(noreplace) %attr(640,root,root) %{_sysconfdir}/libaudit.conf
%{_libdir}/libauparse.so.0
%{_libdir}/libauparse.so.0.*
%{_libdir}/libauplugin.so.1
%{_libdir}/libauplugin.so.1.*
%{_libexecdir}/%{name}/*
%{_tmpfilesdir}/audit.conf
%config(noreplace) %{_sysconfdir}/audit/*
%attr(750,root,root) %dir %{_sysconfdir}/audisp
%attr(750,root,root) %dir %{_sysconfdir}/audisp/plugins.d
%{_unitdir}/audit-rules.service
%{_unitdir}/auditd.service
%dir %{_datadir}/audit-rules
%{_datadir}/audit-rules/*.rules
%{_datadir}/audit-rules/README-rules
%{bash_completions_dir}/audit
%{_mandir}/man*/*

%files devel
%doc contrib/plugin
%{_libdir}/libaudit.so
%{_libdir}/libauparse.so
%{_libdir}/libauplugin.so
%{_includedir}/libaudit.h
%{_includedir}/audit_logging.h
%{_includedir}/audit-records.h
%{_includedir}/auparse.h
%{_includedir}/auparse-defs.h
%{_includedir}/auplugin.h
%{_datadir}/aclocal/audit.m4
%{_libdir}/pkgconfig/audit.pc
%{_libdir}/pkgconfig/auparse.pc
%{_mandir}/man3/*

%changelog
%autochangelog
