# SPDX-FileCopyrightText: (C) 2025 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025 openRuyi Project Contributors
# SPDX-FileContributor: Zheng Junjie <zhengjunjie@iscas.ac.cn>
# SPDX-FileContributor: misaka00251 <liuxin@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

Name:           patch
Version:        2.8
Release:        %autorelease
Summary:        GNU patch
License:        GPL-3.0-or-later
URL:            https://ftp.gnu.org/gnu/patch/
VCS:            git:https://https.git.savannah.gnu.org/git/patch.git
#!RemoteAsset
Source:         https://ftpmirror.gnu.org/gnu/patch/%{name}-%{version}.tar.xz
#!RemoteAsset
Source2:        https://ftpmirror.gnu.org/gnu/patch/%{name}-%{version}.tar.xz.sig
BuildSystem:    autotools

# https://savannah.gnu.org/people/viewgpg.php?user_id=15000
Patch0:         CVE-2019-20633.patch

BuildRequires:  ed

%description
The GNU patch program is used to apply diffs between original and
changed files (generated by the diff command) to the original files.

%check
%make_build check

%files
%doc AUTHORS NEWS README
%license COPYING
%{_bindir}/patch
%{_mandir}/man1/patch.1%{?ext_man}

%changelog
%autochangelog
