# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: misaka00251 <liuxin@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           asm2plan9s
%define go_import_path  github.com/minio/asm2plan9s
# Upstream does not provide git tags, use commit ID instead - 251
%define commit_id cdd76441f9d8c17c52d85f7657da5e8ce55f6083
# TODO: Fix this shit, or not - 251
%define go_test_ignore_failure 1

Name:           go-github-minio-asm2plan9s
Version:        0+git20260108.cdd7644
Release:        %autorelease
Summary:        Tool to generate BYTE sequences for Go assembly as generated by YASM
License:        Apache-2.0
URL:            https://github.com/minio/asm2plan9s
#!RemoteAsset
Source0:        https://github.com/minio/asm2plan9s/archive/%{commit_id}.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildOption(prep):  -n %{_name}-%{commit_id}
BuildOption(check):  -vet=off

BuildRequires:  go
BuildRequires:  go-rpm-macros

Provides:       go(github.com/minio/asm2plan9s) = %{version}

%description
Tool to generate BYTE sequences for Go assembly as generated by YASM/GAS
(for Intel) or GAS (for ARM).

%files
%license LICENSE*
%doc README*
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
