# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           consumer
%define go_import_path  go.opentelemetry.io/collector/consumer

Name:           go-opentelemetry-collector-consumer
Version:        1.58.0
Release:        %autorelease
Summary:        Go module dependency for Prometheus
License:        Apache-2.0
URL:            https://github.com/open-telemetry/opentelemetry-collector
#!RemoteAsset:  sha256:0f697c8512de71d221947b6c63533f2f04a46e1bf8ec9074a6d0af56440e3c95
Source0:        https://github.com/open-telemetry/opentelemetry-collector/archive/refs/tags/consumer/v1.58.0.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildOption(prep):  -n opentelemetry-collector-consumer-v1.58.0/consumer
# The import path is a Go module below the repository root; keep %check scoped
# to this module so GOPATH-mode tests do not scan sibling modules from the archive.
%define go_test_include %{go_import_path}

BuildRequires:  go
BuildRequires:  go(github.com/davecgh/go-spew)
BuildRequires:  go(github.com/hashicorp/go-version)
BuildRequires:  go(github.com/json-iterator/go)
BuildRequires:  go(github.com/modern-go/concurrent)
BuildRequires:  go(github.com/modern-go/reflect2)
BuildRequires:  go(github.com/pmezard/go-difflib)
BuildRequires:  go(github.com/stretchr/testify)
BuildRequires:  go(go.opentelemetry.io/collector/featuregate)
BuildRequires:  go(go.opentelemetry.io/collector/pdata)
BuildRequires:  go(go.opentelemetry.io/collector/pdata/plog)
BuildRequires:  go(go.opentelemetry.io/collector/pdata/pmetric)
BuildRequires:  go(go.opentelemetry.io/collector/pdata/ptrace)
BuildRequires:  go(go.uber.org/goleak)
BuildRequires:  go(go.uber.org/multierr)
BuildRequires:  go(gopkg.in/yaml.v3)
BuildRequires:  go-rpm-macros

Provides:       go(go.opentelemetry.io/collector/consumer) = %{version}
Provides:       go(go.opentelemetry.io/collector/consumer/internal) = %{version}
Provides:       go(go.opentelemetry.io/collector/consumer/xconsumer) = %{version}

Requires:       go(github.com/hashicorp/go-version)
Requires:       go(github.com/json-iterator/go)
Requires:       go(github.com/modern-go/concurrent)
Requires:       go(github.com/modern-go/reflect2)
Requires:       go(go.opentelemetry.io/collector/featuregate)
Requires:       go(go.opentelemetry.io/collector/pdata)
Requires:       go(go.opentelemetry.io/collector/pdata/plog)
Requires:       go(go.opentelemetry.io/collector/pdata/pmetric)
Requires:       go(go.opentelemetry.io/collector/pdata/ptrace)
Requires:       go(go.uber.org/multierr)

%description
Go module dependency for Prometheus. Generated by go2spec.

%files
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
