# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           metric
%define go_import_path  go.opentelemetry.io/otel/metric
%define go_source_subdir metric

Name:           go-opentelemetry-otel-metric
Version:        1.43.0
Release:        %autorelease
Summary:        Go module dependency for Prometheus
License:        Apache-2.0
URL:            https://github.com/open-telemetry/opentelemetry-go
#!RemoteAsset:  sha256:d9068ecbca8e95ffee35e12921b5e88381089348b5be8b11095726c35c3c94ae
Source0:        https://github.com/open-telemetry/opentelemetry-go/archive/refs/tags/metric/v1.43.0.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildOption(prep):  -n opentelemetry-go-metric-v1.43.0
# This package owns a Go module below the repository root; the explicit
# %%install/%%check sections below copy only %%{go_source_subdir}, because
# the default golangmodules phases would copy the full archive under
# %%{go_import_path} and create invalid import paths.

BuildRequires:  go
BuildRequires:  go(github.com/cespare/xxhash/v2)
BuildRequires:  go(github.com/davecgh/go-spew)
BuildRequires:  go(github.com/go-logr/logr)
BuildRequires:  go(github.com/pmezard/go-difflib)
BuildRequires:  go(github.com/stretchr/testify)
BuildRequires:  go(github.com/stretchr/testify/assert)
BuildRequires:  go(github.com/stretchr/testify/require)
BuildRequires:  go(go.opentelemetry.io/auto/sdk)
BuildRequires:  go(go.opentelemetry.io/otel)
BuildRequires:  go(go.opentelemetry.io/otel/attribute)
BuildRequires:  go(go.opentelemetry.io/otel/internal/global)
BuildRequires:  go(go.opentelemetry.io/otel/propagation)
BuildRequires:  go(go.opentelemetry.io/otel/semconv/v1.40.0)
BuildRequires:  go(go.opentelemetry.io/otel/trace)
BuildRequires:  go(gopkg.in/yaml.v3)
BuildRequires:  go-rpm-macros

Provides:       go(go.opentelemetry.io/otel/metric) = %{version}
Provides:       go(go.opentelemetry.io/otel/metric/embedded) = %{version}
Provides:       go(go.opentelemetry.io/otel/metric/noop) = %{version}

Requires:       go(github.com/cespare/xxhash/v2)
Requires:       go(go.opentelemetry.io/otel/attribute)

%description
Go module dependency for Prometheus. Generated by go2spec.

%install
pushd %{go_source_subdir}
%buildsystem_golangmodules_install
popd

%check
pushd %{go_source_subdir}
export GO111MODULE=off
# metric tests import go.opentelemetry.io/otel. Put the system GOPATH first so
# the temporary go.opentelemetry.io/otel/metric tree does not shadow the root
# otel package installed from BuildRequires.
export GOPATH=%{_datadir}/gocode:%{_builddir}/go
mkdir -p %{_builddir}/go/src/%{go_import_path}
cp -a . %{_builddir}/go/src/%{go_import_path}
cd %{_builddir}/go/src/%{go_import_path}
go test -v ./...
popd

%files
%doc metric/README.md
%license LICENSE
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
