# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: sunyuechi <sunyuechi@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%bcond smis 0

Name:           libstoragemgmt
Version:        1.10.2
Release:        %autorelease
Summary:        Storage array management library
License:        LGPL-2.1-or-later
URL:            https://github.com/libstorage/libstoragemgmt
#!RemoteAsset
Source0:        %{url}/releases/download/%{version}/%{name}-%{version}.tar.gz
Source1:        libstoragemgmt.sysusers
BuildSystem:    autotools

# Add systemd sysusers support for user/group management
Patch0:         0001_systemd_ug.patch

BuildOption(conf):  --with-python
%ifnarch %{valgrind_arches}
BuildOption(conf):  --without-mem-leak-test
%endif
BuildOption(conf):  --disable-static
%if %{with smis}
BuildOption(conf):  --with-smispy
%else
BuildOption(conf):  --without-smispy
%endif

BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool
BuildRequires:  make
BuildRequires:  pkgconfig(check)
BuildRequires:  perl
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  systemd
BuildRequires:  bash-completion
BuildRequires:  pkgconfig(bash-completion)
BuildRequires:  libconfig-devel
BuildRequires:  pkgconfig(systemd)
BuildRequires:  procps
BuildRequires:  pkgconfig(sqlite3)
BuildRequires:  python3dist(six)
# Python packaging requirement per Python.md
BuildRequires:  pkgconfig(python3)
BuildRequires:  pkgconfig(ledmon)
BuildRequires:  chrpath
%ifarch %{valgrind_arches}
BuildRequires:  valgrind
%endif
%if %{with smis}
BuildRequires:  python3dist(pywbem)
%endif

Requires:       python-%{name}%{?_isa}
Requires:       ledmon-libs
%{?systemd_requires}

%description
The libStorageMgmt library will provide a vendor agnostic open source storage
application programming interface (API) that will allow management of storage
arrays.  The library includes a command line interface for interactive use and
scripting (command lsmcli).  The library also has a daemon that is used for
executing plug-ins in a separate process (lsmd).

%package        devel
Summary:        Development files for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description    devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.

%package     -n python-%{name}
Summary:        Python client libraries and plug-in support for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}
Requires:       python3dist(six)

# Python packaging requirement per Python.md
Provides:       python3-%{name} = %{version}-%{release}
%python_provide python3-%{name}

%description -n python-%{name}
This contains python client libraries as well as python framework
support and open source plug-ins written in python.

# Merged plugins package per SplitPackage.md - consolidate by feature category
%package        plugins
Summary:        Storage management plugins for %{name}
Requires:       python-%{name} = %{version}-%{release}
Requires:       %{name}%{?_isa} = %{version}-%{release}
Requires:       nfs-utils
%if %{with smis}
Requires:       python3dist(pywbem)
%endif

%description    plugins
The %{name}-plugins package contains all storage management plugins including
support for targetd, LSI MegaRAID (via storcli), HP SmartArray (via hpssacli),
Microsemi Adaptec RAID, local NFS exports, and local storage auto-detection.
%if %{with smis}
Also includes generic SMI-S array support.
%endif

%package        udev
Summary:        Udev files for %{name}

%description    udev
The %{name}-udev package contains udev rules and helper utilities for
uevents generated by the kernel.

%conf -p
./autogen.sh

%install -a
#Files for udev handling
mkdir -p %{buildroot}/%{_udevrulesdir}
install -m 644 tools/udev/90-scsi-ua.rules \
    %{buildroot}/%{_udevrulesdir}/90-scsi-ua.rules
install -m 755 tools/udev/scan-scsi-target \
    %{buildroot}/%{_udevrulesdir}/../scan-scsi-target
install -Dpm0644 %{SOURCE1} %{buildroot}%{_sysusersdir}/%{name}.conf

%pre
%sysusers_create_package %{name} %{SOURCE1}

%post
# Create tmp socket folders.
%tmpfiles_create %{_tmpfilesdir}/%{name}.conf
%systemd_post %{name}.service

%preun
%systemd_preun %{name}.service

%postun
%systemd_postun %{name}.service

# Need to restart lsmd if plugins package is new installed or removed.
%post plugins
if [ $1 -eq 1 ]; then
    # New install.
    /usr/bin/systemctl try-restart %{name}.service >/dev/null 2>&1 || :
fi

%postun plugins
if [ $1 -eq 0 ]; then
    # Remove
    /usr/bin/systemctl try-restart %{name}.service >/dev/null 2>&1 || :
fi

# no test
%check

%files
%doc README COPYING.LIB NEWS
%dir %{_sysconfdir}/lsm
%dir %{_sysconfdir}/lsm/pluginconf.d
%ghost %dir %attr(0775,root,libstoragemgmt) /run/lsm/
%ghost %dir %attr(0775,root,libstoragemgmt) /run/lsm/ipc
%config(noreplace) %{_sysconfdir}/lsm/lsmd.conf
%{_bindir}/lsmcli
%{_bindir}/lsmd
%{_bindir}/simc_lsmplugin
%{_datadir}/bash-completion/completions/lsmcli
%{_libdir}/*.so.*
%{_mandir}/man1/lsmcli.1*
%{_mandir}/man1/lsmd.1*
%{_mandir}/man1/simc_lsmplugin.1*
%{_mandir}/man5/lsmd.conf.5*
%{_sysusersdir}/%{name}.conf
%{_unitdir}/%{name}.service
%attr(0644,root,root) %{_tmpfilesdir}/%{name}.conf

%files devel
%{_includedir}/*
# Development symlink (unversioned .so)
%{_libdir}/*.so
%{_libdir}/pkgconfig/libstoragemgmt.pc
%{_mandir}/man3/lsm_*
%{_mandir}/man3/libstoragemgmt*

%files -n python-libstoragemgmt
%dir %{python_sitearch}/lsm
%{python_sitearch}/lsm/__init__.*
%{python_sitearch}/lsm/_client.*
%{python_sitearch}/lsm/_common.*
%{python_sitearch}/lsm/_local_disk.*
%{python_sitearch}/lsm/_data.*
%{python_sitearch}/lsm/_iplugin.*
%{python_sitearch}/lsm/_pluginrunner.*
%{python_sitearch}/lsm/_transport.*
%{python_sitearch}/lsm/__pycache__/
%{python_sitearch}/lsm/version.*
%dir %{python_sitearch}/lsm/lsmcli
%{python_sitearch}/lsm/lsmcli/__init__.*
%{python_sitearch}/lsm/lsmcli/__pycache__/
%{python_sitearch}/lsm/lsmcli/data_display.*
%{python_sitearch}/lsm/lsmcli/cmdline.*
%{python_sitearch}/lsm/_clib.*

%dir %{python_sitearch}/sim_plugin
%{python_sitearch}/sim_plugin/__pycache__/
%{python_sitearch}/sim_plugin/__init__.*
%{python_sitearch}/sim_plugin/simulator.*
%{python_sitearch}/sim_plugin/simarray.*

%{_bindir}/sim_lsmplugin
%dir %{_libexecdir}/lsm.d
%{_libexecdir}/lsm.d/find_unused_lun.py*
%{_libexecdir}/lsm.d/local_check.py*
%config(noreplace) %{_sysconfdir}/lsm/pluginconf.d/sim.conf
%{_mandir}/man1/sim_lsmplugin.1*

%files plugins
# targetd plugin
%dir %{python_sitelib}/targetd_plugin
%dir %{python_sitelib}/targetd_plugin/__pycache__
%{python_sitelib}/targetd_plugin/__pycache__/*
%{python_sitelib}/targetd_plugin/__init__.*
%{python_sitelib}/targetd_plugin/targetd.*
%{_bindir}/targetd_lsmplugin
%{_mandir}/man1/targetd_lsmplugin.1*

# megaraid plugin
%dir %{python_sitelib}/megaraid_plugin
%dir %{python_sitelib}/megaraid_plugin/__pycache__
%{python_sitelib}/megaraid_plugin/__pycache__/*
%{python_sitelib}/megaraid_plugin/__init__.*
%{python_sitelib}/megaraid_plugin/megaraid.*
%{python_sitelib}/megaraid_plugin/utils.*
%{_bindir}/megaraid_lsmplugin
%config(noreplace) %{_sysconfdir}/lsm/pluginconf.d/megaraid.conf
%{_mandir}/man1/megaraid_lsmplugin.1*

# hpsa plugin
%dir %{python_sitelib}/hpsa_plugin
%dir %{python_sitelib}/hpsa_plugin/__pycache__
%{python_sitelib}/hpsa_plugin/__pycache__/*
%{python_sitelib}/hpsa_plugin/__init__.*
%{python_sitelib}/hpsa_plugin/hpsa.*
%{python_sitelib}/hpsa_plugin/utils.*
%{_bindir}/hpsa_lsmplugin
%config(noreplace) %{_sysconfdir}/lsm/pluginconf.d/hpsa.conf
%{_mandir}/man1/hpsa_lsmplugin.1*

# arcconf plugin
%dir %{python_sitelib}/arcconf_plugin
%dir %{python_sitelib}/arcconf_plugin/__pycache__
%{python_sitelib}/arcconf_plugin/__pycache__/*
%{python_sitelib}/arcconf_plugin/__init__.*
%{python_sitelib}/arcconf_plugin/arcconf.*
%{python_sitelib}/arcconf_plugin/utils.*
%{_bindir}/arcconf_lsmplugin
%config(noreplace) %{_sysconfdir}/lsm/pluginconf.d/arcconf.conf
%{_mandir}/man1/arcconf_lsmplugin.1*

# nfs plugin (has native extension)
%dir %{python_sitearch}/nfs_plugin
%dir %{python_sitearch}/nfs_plugin/__pycache__
%{python_sitearch}/nfs_plugin/__pycache__/*
%{python_sitearch}/nfs_plugin/__init__.*
%{python_sitearch}/nfs_plugin/nfs.*
%{python_sitearch}/nfs_plugin/nfs_clib.*
%config(noreplace) %{_sysconfdir}/lsm/pluginconf.d/nfs.conf
%{_bindir}/nfs_lsmplugin
%{_mandir}/man1/nfs_lsmplugin.1*

# local plugin
%dir %{python_sitelib}/local_plugin
%dir %{python_sitelib}/local_plugin/__pycache__
%{python_sitelib}/local_plugin/__pycache__/*
%{python_sitelib}/local_plugin/__init__.*
%{python_sitelib}/local_plugin/local.*
%config(noreplace) %{_sysconfdir}/lsm/pluginconf.d/local.conf
%{_bindir}/local_lsmplugin
%{_mandir}/man1/local_lsmplugin.1*

%if %{with smis}
# smis plugin
%dir %{python_sitelib}/smispy_plugin
%dir %{python_sitelib}/smispy_plugin/__pycache__
%{python_sitelib}/smispy_plugin/__pycache__/*
%{python_sitelib}/smispy_plugin/__init__.*
%{python_sitelib}/smispy_plugin/smis.*
%{python_sitelib}/smispy_plugin/dmtf.*
%{python_sitelib}/smispy_plugin/utils.*
%{python_sitelib}/smispy_plugin/smis_common.*
%{python_sitelib}/smispy_plugin/smis_cap.*
%{python_sitelib}/smispy_plugin/smis_sys.*
%{python_sitelib}/smispy_plugin/smis_pool.*
%{python_sitelib}/smispy_plugin/smis_disk.*
%{python_sitelib}/smispy_plugin/smis_vol.*
%{python_sitelib}/smispy_plugin/smis_ag.*
%{_bindir}/smispy_lsmplugin
%{_mandir}/man1/smispy_lsmplugin.1*
%endif

%files udev
%{_udevrulesdir}/../scan-scsi-target
%{_udevrulesdir}/90-scsi-ua.rules

%changelog
%autochangelog
