# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           googleapis
%define go_import_path  github.com/gogo/googleapis

Name:           go-github-gogo-googleapis
Version:        1.4.1
Release:        %autorelease
Summary:        Google APIs generated by gogoprotobuf
License:        Apache-2.0
URL:            https://github.com/gogo/googleapis
#!RemoteAsset:  sha256:8606651cad0622952526f0630e7169b9215aa13888c07cac9e30a8360bb7c818
Source0:        https://github.com/gogo/googleapis/archive/v%{version}.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildRequires:  go
BuildRequires:  go-rpm-macros
BuildRequires:  go(github.com/gogo/protobuf)
BuildRequires:  go(google.golang.org/grpc)

Provides:       go(%{go_import_path}) = %{version}

Requires:       go(github.com/gogo/protobuf)
Requires:       go(google.golang.org/grpc)

%description
Google APIs generated by gogoprotobuf for use with gogo/protobuf and gRPC.

%files
%doc Readme.md
%license LICENSE
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
