# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           pdata
%define go_import_path  go.opentelemetry.io/collector/pdata

Name:           go-opentelemetry-collector-pdata
Version:        1.58.0
Release:        %autorelease
Summary:        Go module dependency for Prometheus
License:        Apache-2.0
URL:            https://github.com/open-telemetry/opentelemetry-collector
#!RemoteAsset:  sha256:b35c0e08301dc74db5a1e8d37d5e761595971e93ed06084bd592ebd85c741d36
Source0:        https://github.com/open-telemetry/opentelemetry-collector/archive/refs/tags/pdata/v1.58.0.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildOption(prep):  -n opentelemetry-collector-pdata-v1.58.0/pdata
# The import path is a Go module below the repository root; keep %check scoped
# to this module so GOPATH-mode tests do not scan sibling modules from the archive.
%define go_test_include %{go_import_path}

BuildRequires:  go
BuildRequires:  go(github.com/davecgh/go-spew)
BuildRequires:  go(github.com/hashicorp/go-version)
BuildRequires:  go(github.com/json-iterator/go)
BuildRequires:  go(github.com/modern-go/concurrent)
BuildRequires:  go(github.com/modern-go/reflect2)
BuildRequires:  go(github.com/pmezard/go-difflib)
BuildRequires:  go(github.com/stretchr/testify)
BuildRequires:  go(go.opentelemetry.io/collector/featuregate)
BuildRequires:  go(go.opentelemetry.io/collector/internal/testutil)
BuildRequires:  go(go.opentelemetry.io/proto/slim/otlp)
BuildRequires:  go(go.opentelemetry.io/proto/slim/otlp/collector/profiles/v1development)
BuildRequires:  go(go.opentelemetry.io/proto/slim/otlp/profiles/v1development)
BuildRequires:  go(go.uber.org/goleak)
BuildRequires:  go(go.uber.org/multierr)
BuildRequires:  go(golang.org/x/net)
BuildRequires:  go(golang.org/x/sys)
BuildRequires:  go(golang.org/x/text)
BuildRequires:  go(google.golang.org/genproto/googleapis/rpc)
BuildRequires:  go(google.golang.org/grpc)
BuildRequires:  go(google.golang.org/protobuf)
BuildRequires:  go(gopkg.in/yaml.v3)
BuildRequires:  go-rpm-macros

Provides:       go(go.opentelemetry.io/collector/pdata) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/internal) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/internal/json) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/internal/metadata) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/internal/otelgrpc) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/internal/otlp) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/internal/proto) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/pcommon) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/plog) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/plog/plogotlp) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/pmetric) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/pprofile) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/pmetric/pmetricotlp) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/testdata) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/ptrace) = %{version}
Provides:       go(go.opentelemetry.io/collector/pdata/ptrace/ptraceotlp) = %{version}

Requires:       go(github.com/hashicorp/go-version)
Requires:       go(github.com/json-iterator/go)
Requires:       go(github.com/modern-go/concurrent)
Requires:       go(github.com/modern-go/reflect2)
Requires:       go(go.opentelemetry.io/collector/featuregate)
Requires:       go(go.uber.org/multierr)
Requires:       go(golang.org/x/net)
Requires:       go(golang.org/x/sys)
Requires:       go(golang.org/x/text)
Requires:       go(google.golang.org/genproto/googleapis/rpc)
Requires:       go(google.golang.org/grpc)
Requires:       go(google.golang.org/protobuf)

%description
Go module dependency for Prometheus. Generated by go2spec.

%files
%doc README.md
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
