# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           klog
%define go_import_path  k8s.io/klog/v2
%define commit_id dbd6b2bc8a30833c5191eba666819d8fa2474a26
# Example packages need optional test-only dependencies such as go-logr/zapr,
# go.uber.org/goleak and golang.org/x/tools/go/analysis/analysistest.
%define go_test_exclude_glob %{shrink:
    %{go_import_path}/examples*
}

Name:           go-k8s-klog-v2
Version:        0+git20260319.dbd6b2b
Release:        %autorelease
Summary:        Go module dependency for Prometheus
License:        Apache-2.0
URL:            https://github.com/kubernetes/klog
#!RemoteAsset:  sha256:0ed36af8bf6128726f86df02967284ffa67bf0178785960c8dff4dd7d42b44a1
Source0:        https://github.com/kubernetes/klog/archive/%{commit_id}.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildRequires:  go
BuildRequires:  go(github.com/go-logr/logr)
BuildRequires:  go-rpm-macros

Provides:       go(k8s.io/klog/v2) = %{version}
Provides:       go(k8s.io/klog/v2/ktesting) = %{version}
Provides:       go(k8s.io/klog/v2/ktesting/init) = %{version}
Provides:       go(k8s.io/klog/v2/textlogger) = %{version}

Requires:       go(github.com/go-logr/logr)

%description
Go module dependency for Prometheus. Generated by go2spec.

%files
%doc README.md
%doc CONTRIBUTING.md
%license LICENSE
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
