# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: HNO3Miracle <xiangao.or@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%define _name           api
%define go_import_path  google.golang.org/genproto/googleapis/api
%define commit_id aa98bba5eb94e5dcff65e3ffaf9d216c8252207d
# These deprecated alias packages import the replacement cloud.google.com/go
# client modules, which themselves require this generated API module. Exclude
# only those aliases from %check to avoid a packaging-time dependency cycle.
%define go_test_exclude_glob %{shrink:
    %{go_import_path}/apikeys/v2
    %{go_import_path}/servicecontrol/v1
    %{go_import_path}/servicemanagement/v1
    %{go_import_path}/serviceusage/v1
    %{go_import_path}/serviceusage/v1beta1
}

Name:           go-google-genproto-googleapis-api
Version:        0+git20260519.aa98bba5
Release:        %autorelease
Summary:        Go module dependency for Prometheus
License:        Apache-2.0
URL:            https://github.com/googleapis/go-genproto
#!RemoteAsset:  sha256:81d6931f5f240d25c1e13b62e7c63a5fdd368593280d6f587abd169b4b1d9788
Source0:        https://github.com/googleapis/go-genproto/archive/%{commit_id}.tar.gz#/%{_name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    golangmodules

BuildRequires:  go
BuildRequires:  go(cloud.google.com/go/longrunning)
BuildRequires:  go(golang.org/x/net)
BuildRequires:  go(golang.org/x/sys)
BuildRequires:  go(golang.org/x/text)
BuildRequires:  go(google.golang.org/genproto)
BuildRequires:  go(google.golang.org/genproto/googleapis/rpc)
BuildRequires:  go(google.golang.org/grpc)
BuildRequires:  go(google.golang.org/protobuf)
BuildRequires:  go-rpm-macros

Provides:       go(google.golang.org/genproto/googleapis/api) = %{version}

%description
Go module dependency for Prometheus. Generated by go2spec.

%install
install -dm0755 %{buildroot}%{go_sys_gopath}/%{go_import_path}
cp -a googleapis/api/* %{buildroot}%{go_sys_gopath}/%{go_import_path}/

%check
mkdir -p _build/src/google.golang.org/genproto/googleapis
cp -a googleapis/api _build/src/%{go_import_path}
_go_pkgs=$(GO111MODULE=off GOPATH="$PWD/_build:%{_datadir}/gocode" go list -e -f '{{.ImportPath}}' %{go_import_path}/...)
_go_filtered=""
set -f
for _pkg in ${_go_pkgs}; do
    _skip=0
    for _ex in %{?go_test_exclude_glob}; do
        case "${_pkg}" in ${_ex}) _skip=1 ;; esac
    done
    [ ${_skip} -eq 0 ] && _go_filtered="${_go_filtered} ${_pkg}"
done
set +f
test -n "${_go_filtered}"
GO111MODULE=off GOPATH="$PWD/_build:%{_datadir}/gocode" go test -v ${_go_filtered}

%files
%doc README.md
%license LICENSE
%{go_sys_gopath}/%{go_import_path}

%changelog
%autochangelog
